<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Profil_toggle-sidebar (3)</name>
   <tag></tag>
   <elementGuidId>42da9e20-1398-43c9-8792-cfcfc1f76129</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#toggle-sidebar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='toggle-sidebar']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>edf538f5-e06b-48de-80ee-354906a2a88b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>toggle-sidebar</value>
      <webElementGuid>cde5ab1f-76ba-45e8-9532-e7db6e9eefd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link</value>
      <webElementGuid>170b3c55-5e48-4c3a-9f0c-7bfa4e3ac489</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-widget</name>
      <type>Main</type>
      <value>pushmenu</value>
      <webElementGuid>d7758aca-9e90-4f29-b663-9063a16158b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>dd3a5f20-e8e6-4089-9260-3b330554a528</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4f559f46-b0b5-4fc1-8172-36abac84d3d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;toggle-sidebar&quot;)</value>
      <webElementGuid>2c2fefc4-898b-408a-9131-5e9802ffdd12</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='toggle-sidebar']</value>
      <webElementGuid>994e9e44-ce9b-4b3a-b1ed-51d149188ade</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#')]</value>
      <webElementGuid>ba87a82b-9887-49ff-9dc3-9c8fcf55cede</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>3d932dc5-3029-43fc-b7cd-0ceb5afc614a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'toggle-sidebar' and @href = '#']</value>
      <webElementGuid>7bb1d0cb-6310-4ea6-af46-2afa0ce8a53b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
