<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Financial Integrated Applications - N_141562</name>
   <tag></tag>
   <elementGuidId>f27c2d01-482f-44e6-a2e2-358192066754</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.p-inputtext.p-component.p-element.w-full.ng-untouched.p-filled.ng-dirty.ng-valid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a547f84a-7d51-4c23-8bfb-eb3862cdb50a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>6ee99ecc-c6b1-4e9a-82e9-113bad5e9bf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>4ef523dc-515e-4e95-a24a-fd9af8a83705</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>a999d95a-4181-46e4-9058-5eebae6d872a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component p-element w-full ng-untouched p-filled ng-dirty ng-valid</value>
      <webElementGuid>79c8b7ef-b7c0-4a62-9d71-7bca49b5a60b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/jhi-root[1]/jhi-logingw[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;background-login surface-ground h-screen w-screen flex align-items-center justify-content-center&quot;]/form[@class=&quot;ng-dirty ng-touched ng-valid&quot;]/div[@class=&quot;surface-card py-7 px-5 sm:px-7 shadow-2 flex flex-column w-11 sm:w-30rem&quot;]/div[@class=&quot;login-form&quot;]/span[@class=&quot;p-input-icon-left mb-4&quot;]/input[@class=&quot;p-inputtext p-component p-element w-full ng-untouched p-filled ng-dirty ng-valid&quot;]</value>
      <webElementGuid>71a4f4ff-ec8a-42b5-b61d-0572fcea4e20</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='password']</value>
      <webElementGuid>bdbe4a3e-3fc5-4dfd-8c0b-66e98479e05b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/input</value>
      <webElementGuid>64a7873c-6e00-4a62-a585-204cbd4a7ab8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @placeholder = 'Password']</value>
      <webElementGuid>0be52202-c14f-4df6-9fe7-e329357d14d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
