<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PeTIK MUSTAHIK_LoginFormusername (2)</name>
   <tag></tag>
   <elementGuidId>128ddbe1-4615-445f-bb17-2d0b6c111c24</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#loginform-username</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='loginform-username']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e15ef517-63cf-4cfc-919e-b3d81b018411</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>316779fa-9cab-4d05-bd11-8ac40b450998</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>loginform-username</value>
      <webElementGuid>c5ce33f1-4b97-4018-9ebe-9b53b7452766</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>57f9b4cf-4455-4445-bf3d-3695974eb4d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>LoginForm[username]</value>
      <webElementGuid>c05ce690-68f9-41ed-b8f3-6c7dbcffac27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>4d1d8a50-dd75-4984-b117-b60fcb53700e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c3f81224-fcf3-4a94-b32a-beca0fa8e4d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loginform-username&quot;)</value>
      <webElementGuid>a3b35fc3-d482-48d0-a81b-fc81bb410999</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='loginform-username']</value>
      <webElementGuid>eb8d5c3b-a1f1-464c-9b75-f58882b56d21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='login-form']/div/input</value>
      <webElementGuid>07212d25-3e13-4c1d-9942-d512f7fc6b6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>ec667390-a461-4589-8a3b-d2afb52915c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'loginform-username' and @name = 'LoginForm[username]' and @placeholder = 'Email']</value>
      <webElementGuid>617c56de-ef03-492a-9afc-8971736e2d1e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
