<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PeTIK MUSTAHIK_LoginFormpassword (1)</name>
   <tag></tag>
   <elementGuidId>72177c42-3633-49f9-82e3-3dd769971835</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#loginform-password</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='loginform-password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>62a524c3-477f-418a-9b58-32079b6f951b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>6378b155-0748-4eac-945a-d983fd893ea7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>loginform-password</value>
      <webElementGuid>d051503d-2e77-4eb7-9376-667b98ffd241</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>5702e684-5ce8-4168-9c8a-8e98dd75b756</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>LoginForm[password]</value>
      <webElementGuid>0acad828-7024-4329-ab70-2d5332fb1d39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>3a82209e-d5ab-4cfb-8b01-7a5b6886a6c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b7b43c59-9960-430f-8dfc-d7224277ac59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loginform-password&quot;)</value>
      <webElementGuid>664f7d28-a48b-43f7-9bb9-3e0938fb31e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='loginform-password']</value>
      <webElementGuid>1c15089f-162e-49c0-9963-350950514b9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='login-form']/div[2]/input</value>
      <webElementGuid>ddef14f9-dc0c-4f0a-85a9-11a42e7b0c2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>2c07ef93-a02a-4ef5-ae03-dd516d25bf7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'loginform-password' and @name = 'LoginForm[password]' and @placeholder = 'Password']</value>
      <webElementGuid>40e0e7f6-1b78-4dd3-8deb-62e4db31a807</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
