<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Telepon_Mustahiktelepon</name>
   <tag></tag>
   <elementGuidId>15432a05-3672-423a-9ad4-cfdfa45b794b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mustahik-telepon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mustahik-telepon']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5336ea9f-f968-424d-a3ff-5f6b6142b81f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>31298a06-98d7-4e1e-9470-180a01da63c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mustahik-telepon</value>
      <webElementGuid>70cc2429-6882-4279-84df-dd6786334c71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c76d3017-a902-4734-983d-6b0bfa558679</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Mustahik[telepon]</value>
      <webElementGuid>e3ca5dd5-3e5a-4753-9c7e-17adaa4e9b73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>083845804927</value>
      <webElementGuid>bbb6759a-4636-4860-a39e-38fbc4773a6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mustahik-telepon&quot;)</value>
      <webElementGuid>c0e6cd43-031e-47e2-ac44-a3cccb83cdd6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mustahik-telepon']</value>
      <webElementGuid>adfde1d4-8b55-462e-8bcf-e1697ff09b7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='create-mustahik']/div/div/div[6]/input</value>
      <webElementGuid>0cfff313-0ea9-4ff1-bc46-bfe9b4430b28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/input</value>
      <webElementGuid>7ff4e8c0-6630-4554-8581-fc0487f1966e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'mustahik-telepon' and @name = 'Mustahik[telepon]']</value>
      <webElementGuid>0d6cb5e3-b8b0-40e9-b33a-a2a490636975</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
