<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_-- Pilih --_p-dropdown-trigger ng-tns-c70-33</name>
   <tag></tag>
   <elementGuidId>7a0eccb7-a5e6-4952-aaaa-1908d85ef21e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.p-dropdown-trigger.ng-tns-c70-33</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p-dropdown[@id='timPemeriksaBarang']/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5f5aa12b-dde4-4541-a788-e61bfa6d99a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1a17edc5-7413-47ec-9153-10912f7f1ad5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>dropdown trigger</value>
      <webElementGuid>0b8c458e-31c1-424c-8f10-98c9cb075a77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>3ec23294-d409-407a-8bad-4f8abec4aed6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-dropdown-trigger ng-tns-c70-33</value>
      <webElementGuid>a5c2c5a5-4abd-4e0b-acd4-3a29943d55ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;timPemeriksaBarang&quot;)/div[@class=&quot;ng-tns-c70-33 p-dropdown p-component p-dropdown-clearable&quot;]/div[@class=&quot;p-dropdown-trigger ng-tns-c70-33&quot;]</value>
      <webElementGuid>b4a5dceb-ab58-4a9b-af33-44d090d0cb81</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p-dropdown[@id='timPemeriksaBarang']/div/div[2]</value>
      <webElementGuid>1ffc4a55-1886-4e07-a3fc-ec5c77f7e9f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-- Pilih --'])[1]/following::div[1]</value>
      <webElementGuid>ba5f6662-bd38-4f05-9f90-38a2432b8ec6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tim Pemeriksa Barang'])[1]/following::div[4]</value>
      <webElementGuid>ba434397-50c2-48d7-af24-931224e23168</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tim Pemeriksa Jasa'])[1]/preceding::div[1]</value>
      <webElementGuid>031fd7ac-e350-4966-9efe-c0040fc7a009</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tim Pemeriksa Penyelesaian Pekerjaan'])[1]/preceding::div[2]</value>
      <webElementGuid>4e597413-5471-4a84-998f-7d69f47a05b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/p-dropdown/div/div[2]</value>
      <webElementGuid>de6bfb04-a3a3-4ab9-b95e-9b18464688fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
