<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Garansi_garansi</name>
   <tag></tag>
   <elementGuidId>d7df8055-33bd-40b1-8199-96a0dac806d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#garansi</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='garansi']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f1c2489f-9ac4-4006-8a3d-28393416d43c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>24a57978-1d15-447b-9f6a-01a0f2df7804</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>garansi</value>
      <webElementGuid>1b276203-560f-4d5e-a5e9-97478d933434</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>garansi</value>
      <webElementGuid>22be86c7-b0f3-445e-b164-3fa29eecb5d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>66e45f35-e486-4d92-b9e8-058c5a6711bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-sm text-color surface-overlay p-2 border-1 border-solid border-500 appearance-none outline-none focus:border-primary w-full h-custom ng-untouched ng-valid ng-dirty</value>
      <webElementGuid>ddd0896a-4658-445e-890e-3a7ba0a27f85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;garansi&quot;)</value>
      <webElementGuid>737adc21-479a-459c-a2d9-545cbe40e241</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='garansi']</value>
      <webElementGuid>f4189483-0cac-46aa-b4d0-1fa7459a40e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div[2]/input</value>
      <webElementGuid>a191ee14-ddac-4ec1-9c00-0a14e5978193</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'garansi' and @placeholder = '0']</value>
      <webElementGuid>76dbbbca-4d11-4127-8df6-d54cd5c08a84</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
