<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Retensi_retensi</name>
   <tag></tag>
   <elementGuidId>7137626c-3e8b-4dc8-b6dd-ae3bc5e5a672</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#retensi</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='retensi']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>57c8c837-0165-4550-88ba-bfc8412b03fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>8c262107-8691-4c0e-a29b-aa0229bc2548</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>retensiPersen</value>
      <webElementGuid>aa3db821-8aba-45b8-ac68-3bac16f202b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>retensi</value>
      <webElementGuid>218fe0c6-cf52-4d0f-a9bb-1b2f2c4effaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-sm text-color surface-overlay p-2 border-1 border-solid border-500 appearance-none outline-none focus:border-primary w-full ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>0d74bbc8-54fd-4dde-87a2-84fce655573e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;retensi&quot;)</value>
      <webElementGuid>51ab4484-7dae-49cd-bd54-7388a11ea0b5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='retensi']</value>
      <webElementGuid>4ca56033-68e7-4446-b67b-bd455a40a9e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/input</value>
      <webElementGuid>34744200-1b1d-4367-af09-7408f8f2c5af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'retensi']</value>
      <webElementGuid>e3be32fe-5dcf-44f8-a43f-734be1008f50</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
