<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Judul Kontrak_judulKontrak</name>
   <tag></tag>
   <elementGuidId>d16828c2-7e7a-4a7d-b51a-671828f18815</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#judulKontrak</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='judulKontrak']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>6ba8cc4d-b7e9-46c4-bc66-2bab979051c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>judulKontrak</value>
      <webElementGuid>c644a3e4-bd4b-4c33-93d9-634a3ac39965</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>judulKontrak</value>
      <webElementGuid>a8a76fdf-800c-433c-8b62-03150ed05a90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0a483ef3-9d7d-4fc7-aff8-b6c78b8b7ca8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>a9ff9dc0-054a-4214-88e7-b654c2eeceab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-base text-color surface-overlay p-2 border-1 border-solid border-500 appearance-none outline-none focus:border-primary w-full ng-untouched ng-dirty ng-valid</value>
      <webElementGuid>80c47fdc-23b7-4670-9d87-b6e025b20ba1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;judulKontrak&quot;)</value>
      <webElementGuid>e87f8b60-256b-494d-87b0-f7281527f485</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='judulKontrak']</value>
      <webElementGuid>6d110152-1c51-4bb4-a973-f1f0667cc576</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>39b9470c-4407-4f1a-ac96-66a54278787e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'judulKontrak' and @type = 'text']</value>
      <webElementGuid>dd2e00c4-537d-49f0-88df-c7b846d9268a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
