<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Mustahik_Mustahiknama</name>
   <tag></tag>
   <elementGuidId>84652884-bcf6-41ea-88bd-ef89710708c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mustahik-nama</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mustahik-nama']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4bbbd360-2185-445a-b453-9b649308c0d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ddf3d103-5244-447c-ad47-cbf93593c5c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mustahik-nama</value>
      <webElementGuid>219477e0-4b95-4779-8dcc-e7348203a651</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>024f3708-f563-4b06-8805-b5a5f8b40571</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Mustahik[nama]</value>
      <webElementGuid>2edf1a7b-d0c1-4226-9c7f-fbc6834ab818</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mustahik-nama&quot;)</value>
      <webElementGuid>1712ea5b-0fec-4851-b0a1-78110293c157</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mustahik-nama']</value>
      <webElementGuid>7455c51c-9250-407f-af7f-624b021e6b44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='create-mustahik']/div/div/div/input</value>
      <webElementGuid>46fcf28c-6ed8-4455-96f7-c070246820b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>93aec21c-7179-425f-b4ae-0570f220ba13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'mustahik-nama' and @name = 'Mustahik[nama]']</value>
      <webElementGuid>8a0ebb31-2002-4fb1-9e07-a94a19f257c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
