<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tanggal Daftar_Mustahiktanggal_daftar</name>
   <tag></tag>
   <elementGuidId>9d00caa9-d677-418e-8126-a3a3e03089c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mustahik-tanggal_daftar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mustahik-tanggal_daftar']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fca46045-5827-416e-8e72-522ea059281c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>64c8d5a9-1734-4c11-be8d-c27b9a785b1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mustahik-tanggal_daftar</value>
      <webElementGuid>3a6fc38c-61ff-419b-97be-4ece51147a39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control krajee-datepicker</value>
      <webElementGuid>b50f91a7-0279-4981-9a2d-6259f2b42c63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Mustahik[tanggal_daftar]</value>
      <webElementGuid>13b2fa1b-b91b-4b2e-b031-27c36910a36d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>dd-mm-yyyy</value>
      <webElementGuid>196f5093-a841-438c-a054-31a806f52ae5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-datepicker-source</name>
      <type>Main</type>
      <value>mustahik-tanggal_daftar</value>
      <webElementGuid>72f76ac2-df32-4ec7-b16f-2648aa087056</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-datepicker-type</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>06031b62-e484-4d9f-83ba-88512c0aa2b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-krajee-kvdatepicker</name>
      <type>Main</type>
      <value>kvDatepicker_4e024ef8</value>
      <webElementGuid>aa1ecbec-dc19-42fc-854f-7d841920d1d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mustahik-tanggal_daftar&quot;)</value>
      <webElementGuid>57660db2-99c8-44eb-9435-8022ace8925f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mustahik-tanggal_daftar']</value>
      <webElementGuid>2358e7b2-6275-4102-a8c1-cd473816bdf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='create-mustahik']/div/div/div[10]/input</value>
      <webElementGuid>640b23b1-777d-4418-bffc-1df5ad6a4683</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/input</value>
      <webElementGuid>5227c32c-3a34-4923-a12d-3460560151fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'mustahik-tanggal_daftar' and @name = 'Mustahik[tanggal_daftar]' and @placeholder = 'dd-mm-yyyy']</value>
      <webElementGuid>9253e3e4-8f27-491b-a8d2-512b0e0d8558</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
