<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tanggal Lahir_Mustahiktanggal_lahir</name>
   <tag></tag>
   <elementGuidId>d905486f-249e-4445-b549-a6626583d65c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mustahik-tanggal_lahir</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mustahik-tanggal_lahir']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>47da28bb-ea9d-481c-a9f6-a2de3a556f2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a852953d-8dcb-4c0f-a022-48bb0cc9f37d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mustahik-tanggal_lahir</value>
      <webElementGuid>eb103c91-2a89-4ba0-a5e4-a2e562d7696a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control krajee-datepicker</value>
      <webElementGuid>70e3bb62-46b7-4f92-abf4-73123e01a033</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Mustahik[tanggal_lahir]</value>
      <webElementGuid>6d2490e5-233b-4c85-9ddb-fc1332827d70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>dd-mm-yyyy</value>
      <webElementGuid>e81275d5-89ee-46b0-b234-2c643be4bbfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-datepicker-source</name>
      <type>Main</type>
      <value>mustahik-tanggal_lahir</value>
      <webElementGuid>9af16565-44b7-4f86-8405-d79fa313441c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-datepicker-type</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>fce9c674-eaba-4921-9594-76417306caaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-krajee-kvdatepicker</name>
      <type>Main</type>
      <value>kvDatepicker_cb1a2551</value>
      <webElementGuid>878689b0-8b0d-4266-8ba5-db109c523c8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mustahik-tanggal_lahir&quot;)</value>
      <webElementGuid>7731060a-23b2-4e24-84e9-063b69df886f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mustahik-tanggal_lahir']</value>
      <webElementGuid>06de09f6-3a21-4748-a0af-e7c1de7e1772</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='create-mustahik']/div/div/div[4]/input</value>
      <webElementGuid>25950a5b-e37a-49fa-8921-80bf11dce6ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>7e6ce9a1-d068-435a-a595-c8c9be4551c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'mustahik-tanggal_lahir' and @name = 'Mustahik[tanggal_lahir]' and @placeholder = 'dd-mm-yyyy']</value>
      <webElementGuid>337d54d0-9b1a-49c3-86de-118954a8bca9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
