<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tempat Lahir_Mustahiktempat_lahir</name>
   <tag></tag>
   <elementGuidId>433f91cf-26d8-416a-a334-88809952fd13</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mustahik-tempat_lahir</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mustahik-tempat_lahir']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>11c9ff4d-1f18-4fbb-88f1-6342ca69a553</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>de0a8966-bed7-4b7e-8753-d4e9d5495eb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mustahik-tempat_lahir</value>
      <webElementGuid>b96016b5-a855-4d4b-91f1-6da5f7996970</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>205feda1-8188-469e-ae9e-79293e4a94da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Mustahik[tempat_lahir]</value>
      <webElementGuid>f702e56a-3a10-4112-af21-91cb08562fdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mustahik-tempat_lahir&quot;)</value>
      <webElementGuid>5934cafc-7a78-4e28-860a-0cf7848130f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mustahik-tempat_lahir']</value>
      <webElementGuid>05b09ffd-aad9-4096-9760-f5a384f365b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='create-mustahik']/div/div/div[3]/input</value>
      <webElementGuid>ed792b2a-9cbb-4dc0-8952-84e9521ae90e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>80098662-c8f9-45a8-ac2d-185271386840</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'mustahik-tempat_lahir' and @name = 'Mustahik[tempat_lahir]']</value>
      <webElementGuid>51fe5fbd-68e8-47bd-8dd7-9704429b97a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
