<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Alamat sesuai KK (apabila alamat sesu_f87f6b</name>
   <tag></tag>
   <elementGuidId>2fe51fa6-8389-438a-8211-10dccf0367ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mustahik-checked_domisili</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mustahik-checked_domisili']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f674e533-26c4-4959-9639-edcd7d6ee5f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>25330b74-3bfd-43ba-9df8-c20c26e5c982</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mustahik-checked_domisili</value>
      <webElementGuid>30e8a6f4-0dd9-4cd7-9ec2-9103d025854f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Mustahik[checked_domisili]</value>
      <webElementGuid>20fd2029-70f4-4ffe-972d-b5411b483c72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>3c46533d-f8ad-42b4-8091-b69fda395ef8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mustahik-checked_domisili&quot;)</value>
      <webElementGuid>07a3b61c-6618-4fd9-afac-0b1bdacc4f8e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mustahik-checked_domisili']</value>
      <webElementGuid>4be08817-b93d-4f95-bbfe-5670c18eaa51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='create-mustahik']/div/div[2]/div[2]/div[2]/div/label/input</value>
      <webElementGuid>0e949978-16ed-447a-9102-e25cd987beda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>143326b4-2b9f-4ea0-92e0-ff60447b14b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'mustahik-checked_domisili' and @name = 'Mustahik[checked_domisili]']</value>
      <webElementGuid>dc345c62-46ba-40f7-8709-014eff7d6242</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
