<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-- Pilih KelurahanDesa --BITUNG BARA_f5eb98</name>
   <tag></tag>
   <elementGuidId>a799a637-a62f-49a2-91e5-633a817ae5be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mustahik-desa_id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='mustahik-desa_id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>46ca4353-8a99-4886-8b9b-5b2bf8c2917d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mustahik-desa_id</value>
      <webElementGuid>cb8964c8-2d50-4a2a-b923-a1deabe49f53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>11f35c09-df24-41ef-a85e-f27db4660caf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Mustahik[desa_id]</value>
      <webElementGuid>aebe8ff4-9131-4c2c-a3b8-a918e8f5bf61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Pilih Kelurahan/Desa --BITUNG BARAT DUABITUNG BARAT SATUBITUNG TENGAHBITUNG TIMURKAKENTURAN DUAKAKENTURAN SATUPAKADOODANPATETEN TIGA</value>
      <webElementGuid>5f6f2060-ee73-458b-a332-4144715d7a39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mustahik-desa_id&quot;)</value>
      <webElementGuid>7947b5e5-694f-4b05-a313-a6a764cceac5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='mustahik-desa_id']</value>
      <webElementGuid>42cdf109-4aab-4c5a-ade3-162cf4ec6965</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='create-mustahik']/div/div[2]/div/div[2]/div/div[4]/div/select</value>
      <webElementGuid>c39a5306-c4f8-4399-8fe0-7bc9a4ae6be3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kelurahan / Desa'])[1]/following::select[1]</value>
      <webElementGuid>2d1cc161-5ffd-4e46-938c-f5b1b96c78e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kecamatan'])[1]/following::select[2]</value>
      <webElementGuid>f22c1606-fb0d-4b5e-b2c9-dfa2310f61ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alamat Rumah'])[1]/preceding::select[1]</value>
      <webElementGuid>f9001e28-83fd-4451-a552-6aa6c0646f44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alamat Domisili'])[1]/preceding::select[1]</value>
      <webElementGuid>6a393204-b15c-4d6e-b188-863978c9afd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/select</value>
      <webElementGuid>a892a9a5-41f9-4ddd-8142-77c7fadde38f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'mustahik-desa_id' and @name = 'Mustahik[desa_id]' and (text() = '-- Pilih Kelurahan/Desa --BITUNG BARAT DUABITUNG BARAT SATUBITUNG TENGAHBITUNG TIMURKAKENTURAN DUAKAKENTURAN SATUPAKADOODANPATETEN TIGA' or . = '-- Pilih Kelurahan/Desa --BITUNG BARAT DUABITUNG BARAT SATUBITUNG TENGAHBITUNG TIMURKAKENTURAN DUAKAKENTURAN SATUPAKADOODANPATETEN TIGA')]</value>
      <webElementGuid>74902de7-f617-44e4-95cb-047172e208cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
