<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Alamat Rumah_Mustahikalamat</name>
   <tag></tag>
   <elementGuidId>5de9822c-b0c8-415a-9724-f0ae4cccb2bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mustahik-alamat</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='mustahik-alamat']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>2b69cdcf-cf4b-4ff8-8905-852323ce3018</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mustahik-alamat</value>
      <webElementGuid>8b602112-14b4-4e60-9d4b-7b0f166021fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>2785d842-3bbc-4024-9932-c9164f3f1ec8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Mustahik[alamat]</value>
      <webElementGuid>f1c9210a-8fda-4f2a-8336-89d9c1a70d7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>337d6676-677e-4a61-88fd-fc504645e97e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mustahik-alamat&quot;)</value>
      <webElementGuid>10273c98-8e50-4597-bca1-f18ece6a4f1d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='mustahik-alamat']</value>
      <webElementGuid>691c5a06-34fe-4a39-be3e-380d7aee32e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='create-mustahik']/div/div[2]/div/div[2]/div[2]/textarea</value>
      <webElementGuid>732abfde-b5e4-4363-a15d-cc2704b21047</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>ca64fdef-0e18-49a6-ac09-672e11cffc87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'mustahik-alamat' and @name = 'Mustahik[alamat]']</value>
      <webElementGuid>6ed0f01f-7854-421b-9065-4a3622d1245b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
